apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/kikplate/kikplate-api
    newName: kikplate-api
    newTag: dev-local
  - name: ghcr.io/kikplate/kikplate-web
    newName: kikplate-web
    newTag: dev-local-v2
patches:
  - path: api-deployment-patch.yaml
  - path: web-deployment-patch.yaml
  - path: sync-deployment-patch.yaml
