apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ include "kikplate.namespace" . }}
  labels:
    {{- include "kikplate.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.service.port }}
              name: http
          envFrom:
            - secretRef:
                name: app-credentials
          env:
            - name: CONFIG_PATH
              value: /app/config/config.yaml
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: app-config
              mountPath: /app/config/config.yaml
              subPath: config.yaml
              readOnly: true
          readinessProbe:
            httpGet:
              path: /hello
              port: http
            initialDelaySeconds: {{ .Values.api.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /hello
              port: http
            initialDelaySeconds: {{ .Values.api.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.api.livenessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      volumes:
        - name: app-config
          configMap:
            name: app-config
