apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ include "kikplate.namespace" . }}
  labels:
    {{- include "kikplate.labels" . | nindent 4 }}
spec:
  selector:
    app: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
