apiVersion: v1
entries:
  kikplate:
    - apiVersion: v2
      appVersion: latest
      created: ""
      description: Kikplate – the home of your starter boilerplates.
      digest: ""
      home: https://github.com/kikplate/kikplate
      icon: https://raw.githubusercontent.com/kikplate/kikplate/main/web/public/kikplate-logo-on-dark.svg
      keywords:
        - kikplate
        - boilerplate
        - starter
        - templates
      maintainers:
        - name: kikplate
          url: https://github.com/kikplate
      name: kikplate
      sources:
        - https://github.com/kikplate/kikplate
      urls:
        - https://kikplate.github.io/kikplate/kikplate-0.1.0.tgz
      version: 0.1.0
generated: ""
